Update build and publish workflow

diff --git a/.github/workflows/build-and-publish.yml b/.github/workflows/build-and-publish.yml
--- a/.github/workflows/build-and-publish.yml
+++ b/.github/workflows/build-and-publish.yml
@@ -2,18 +2,18 @@ name: Build and Publish
 
 on:
   push:
-    branches: [main]
+    branches: [cure-master]
   pull_request:
-    branches: [main]
+    branches: [cure-master]
   workflow_dispatch:
 
 env:
-  IMAGE_NAME: bahmni/bahmni-apps-frontend
+  IMAGE_NAME: us-east1-docker.pkg.dev/cure-emr-gcp/bahmni/bahmni-apps-frontend
   NODE_VERSION: "22"
 
 jobs:
   lint-and-test:
-    runs-on: ubuntu-latest  
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -30,8 +30,6 @@ jobs:
       - name: Lint code
         run: npx nx run-many --target=lint
 
-      # - name: Lint styles
-      #   run: yarn lint:styles
       - name: Build dependencies first
         run: |
           npx nx build @bahmni/services
@@ -56,17 +54,9 @@ jobs:
     permissions:
       contents: read
       packages: write
-    env:
-      HELM_CHART_PATH: helm/
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
-
-      - name: Set env.ARTIFACT_VERSION
-        run: |
-          wget -q https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/setArtifactVersion.sh && chmod +x setArtifactVersion.sh
-          ./setArtifactVersion.sh .appversion
-          rm setArtifactVersion.sh  
 
       - name: Set up Node.js
         uses: actions/setup-node@v4
@@ -89,11 +79,15 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
-      - name: Login to GitHub Container Registry
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+
+      - name: Login to GAR
         uses: docker/login-action@v3
         with:
-          username: ${{ secrets.DOCKER_HUB_USERNAME }}
-          password: ${{ secrets.DOCKER_HUB_TOKEN }}
+          registry: us-east1-docker.pkg.dev
+          username: _json_key
+          password: ${{ secrets.CURE_EMR_DEPLOYMENTS_SERVICE_ACCOUNT_KEY }}
 
       # Build and push to a temporary tag for scanning
       - name: Build and push multi-arch image (temp)
@@ -124,39 +118,26 @@ jobs:
           # Tag the scanned image with final tags
           docker buildx imagetools create \
             --tag ${{ env.IMAGE_NAME }}:latest \
-            --tag ${{ env.IMAGE_NAME }}:${{ env.ARTIFACT_VERSION }} \
+            --tag ${{ env.IMAGE_NAME }}:${{ github.run_number }} \
             ${{ env.IMAGE_NAME }}:scan-${{ github.sha }}
 
-      - name: Update Version and Image Tag
+  trigger-workflow:
+    name: Trigger workflow to deploy to Docker env
+    needs:
+      - build-and-publish
+    runs-on: ubuntu-latest
+    env:
+      EVENT_TYPE: bahmni-apps-frontend-event
+      ORG_NAME: cureinternational
+      REPOSITORY_NAME: cure-bahmni-docker
+    steps:
+      - name: Create repository_dispatch
         run: |
-          yq --inplace '.image.tag = "${{ env.ARTIFACT_VERSION }}"' $HELM_CHART_PATH/values.yaml
-          yq --inplace '.version = "${{ env.ARTIFACT_VERSION }}"' $HELM_CHART_PATH/Chart.yaml
-      - name: Helm Lint
-        run: helm lint $HELM_CHART_PATH
-
-      - name: Helm Package
-        run: helm package $HELM_CHART_PATH
-
-      - name: Checkout Charts Repository
-        uses: actions/checkout@v2
-        with:
-          repository: Bahmni/helm-charts
-          ref: gh-pages
-          path: helm-charts
-          persist-credentials: false
-
-      - name: Copy Helm Archive
-        run: mkdir -p helm-charts/bahmni-apps-frontend/ && cp bahmni-apps-frontend-${{ env.ARTIFACT_VERSION }}.tgz helm-charts/bahmni-apps-frontend/
-
-      - name: Helm Index
-        working-directory: helm-charts/
-        run: helm repo index --merge index.yaml --url https://bahmni.github.io/helm-charts/  .
-
-      - name: Commit and Push Chart Repository
-        working-directory: helm-charts/
-        run: |
-          git config user.name ${{ secrets.BAHMNI_USERNAME}}
-          git config user.email ${{ secrets.BAHMNI_EMAIL}}
-          git add .
-          git commit -m "Release of bahmni-apps-frontend-${{ env.ARTIFACT_VERSION }}"
-          git push 'https://${{ secrets.BAHMNI_USERNAME}}:${{ secrets.BAHMNI_PAT}}@github.com/bahmni/helm-charts.git' gh-pages
+          trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.CURE_EMR_ORG_ACCESS_TOKEN }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
+          if [ $trigger_result == 204 ];then
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
+          else
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
+            cat trigger_response.txt
+            exit 1
+          fi
